<a href="https://colab.research.google.com/github/marsggbo/AutoMLDemos/blob/master/ch4/nasbench101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NAS-Bench-101 官方实现版本

## 1.1 安装 hyperbox

In [1]:
!pip install git+https://github.com/marsggbo/hyperbox.git

  Cloning https://github.com/marsggbo/hyperbox.git to /tmp/pip-req-build-84rmrakg
  Running command git clone --filter=blob:none --quiet https://github.com/marsggbo/hyperbox.git /tmp/pip-req-build-84rmrakg
  Resolved https://github.com/marsggbo/hyperbox.git to commit c78e965f8f840d223c0efa2e221c0adbb0224d97
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 800.3/800.3 kB 8.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 805.2/805.2 kB 14.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 252.5/252.5 kB 13.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.1/151.1 kB 13.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 21.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 203.7/203.7 kB 10.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 26.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.2/91.2 kB 11.2 MB/s eta 0:00:00
     ━

## 1.2 下载安装

如果使用的是Tensorflow 1.x版本，请使用以下命令安装：

In [ ]:
!pip install git+https://github.com/google-research/nasbench.git

如果使用Tensorflow 2.x版本，请使用以下命令安装：

In [2]:
!pip install git+https://github.com/gabikadlecova/nasbench.git
!pip install protobuf==3.20.0

  Cloning https://github.com/gabikadlecova/nasbench.git to /tmp/pip-req-build-pzht18lo
  Running command git clone --filter=blob:none --quiet https://github.com/gabikadlecova/nasbench.git /tmp/pip-req-build-pzht18lo
  Resolved https://github.com/gabikadlecova/nasbench.git to commit cb2d12cf2905220c4f59fc1811e567742e5fed47
  Preparing metadata (setup.py) ... done
  Created wheel for nasbench: filename=nasbench-1.0-py3-none-any.whl size=46790 sha256=93515fe54a960e1f3619d391b88da9a08e28a919191398bc7e0645a10412b9cc
  Stored in directory: /tmp/pip-ephem-wheel-cache-pox485e4/wheels/a6/0b/2d/91f1655d166581850963b310b09ca2204ede469aa9b35be37e
Successfully built nasbench
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 9.2 MB/s eta 0:00:00
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.20.3
    Uninstalling protobuf-3.20.3:
      Successfully uninstalled protobuf-3.20.3
ERROR: pip's dependency resolver does not currently take into account all the packages t

## 2. 下载查询数据库

- 下载 *nasbench_only108.tfrecord*: 提供的是对每个模型训练108 epochs后的实验数据。

In [3]:
!wget https://storage.googleapis.com/nasbench/nasbench_only108.tfrecord

--2023-10-06 04:17:41--  https://storage.googleapis.com/nasbench/nasbench_only108.tfrecord
Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.2.207, 74.125.137.207, 2607:f8b0:4023:c0d::cf
Connecting to storage.googleapis.com (storage.googleapis.com)|142.251.2.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 522767376 (499M) [application/octet-stream]
Saving to: ‘nasbench_only108.tfrecord’

nasbench_only108.tf 100%[===================>] 498.55M  87.1MB/s    in 6.3s    

2023-10-06 04:17:47 (78.6 MB/s) - ‘nasbench_only108.tfrecord’ saved [522767376/522767376]



- 下载 *nasbench_full.tfrecord*: 提供的是完整的实验数据，包含了不同训练时长（4,12,36,108小时）的实验数据。

In [4]:
!wget https://storage.googleapis.com/nasbench/nasbench_full.tfrecord

--2023-10-06 04:17:48--  https://storage.googleapis.com/nasbench/nasbench_full.tfrecord
Resolving storage.googleapis.com (storage.googleapis.com)... 142.251.2.207, 74.125.137.207, 2607:f8b0:4023:c0d::cf
Connecting to storage.googleapis.com (storage.googleapis.com)|142.251.2.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2085986016 (1.9G) [application/octet-stream]
Saving to: ‘nasbench_full.tfrecord’

nasbench_full.tfrec 100%[===================>]   1.94G  56.0MB/s    in 39s     

2023-10-06 04:18:27 (51.0 MB/s) - ‘nasbench_full.tfrecord’ saved [2085986016/2085986016]



In [5]:
# 将下载的数据库移动到如下路径，方便模型自动读取信息

!mkdir -p ~/.hyperbox/nasbench101
!mv nasbench_only108.tfrecord ~/.hyperbox/nasbench101
!mv nasbench_full.tfrecord ~/.hyperbox/nasbench101

## 3. NAS-Bench-101 官方代码使用示例

In [9]:
# 1. 读取数据库

from nasbench import api
query_file = os.path.expanduser('~/.hyperbox/nasbench101/nasbench_full.tfrecord')
nasbench = api.NASBench(query_file) # 读取数据库可能会耗费较长时间，需耐心等待

Loading dataset from file... This may take a few minutes...
Loaded dataset in 253 seconds


In [10]:
# 2. 预定义相关变量

# Useful constants
INPUT = 'input'
OUTPUT = 'output'
CONV3X3 = 'conv3x3-bn-relu'
CONV1X1 = 'conv1x1-bn-relu'
MAXPOOL3X3 = 'maxpool3x3'
NUM_VERTICES = 7
MAX_EDGES = 9
EDGE_SPOTS = NUM_VERTICES * (NUM_VERTICES - 1) / 2   # Upper triangular matrix
OP_SPOTS = NUM_VERTICES - 2   # Input/output vertices are fixed
ALLOWED_OPS = [CONV3X3, CONV1X1, MAXPOOL3X3]
ALLOWED_EDGES = [0, 1]   # Binary adjacency matrix


In [11]:
# 3. 查询模型性能

# 从数据集中查询类似Inception的单元结构。
cell = api.ModelSpec(
  matrix=[[0, 1, 1, 1, 0, 1, 0],    # 输入层
          [0, 0, 0, 0, 0, 0, 1],    # 1x1卷积
          [0, 0, 0, 0, 0, 0, 1],    # 3x3卷积
          [0, 0, 0, 0, 1, 0, 0],    # 5x5卷积（由两个3x3卷积替代）
          [0, 0, 0, 0, 0, 0, 1],    # 5x5卷积（由两个3x3卷积替代）
          [0, 0, 0, 0, 0, 0, 1],    # 3x3最大池化
          [0, 0, 0, 0, 0, 0, 0]],   # 输出层

  ops=[INPUT, CONV1X1, CONV3X3, CONV3X3, CONV3X3, MAXPOOL3X3, OUTPUT] # 模块顶点的操作，与矩阵的顺序相匹配。
  )

# 多次查询可能会产生不同的结果。每个单元在每个训练轮次内被评估3次，并且查询将随机抽样其中一个结果。
data = nasbench.query(cell)
for k, v in data.items():
    print('%s: %s' % (k, str(v)))


module_adjacency: [[0 1 1 1 1 0 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0]]
module_operations: ['input', 'conv3x3-bn-relu', 'conv1x1-bn-relu', 'maxpool3x3', 'conv3x3-bn-relu', 'conv3x3-bn-relu', 'output']
trainable_parameters: 2694282
training_time: 1154.361083984375
train_accuracy: 1.0
validation_accuracy: 0.9336938858032227
test_accuracy: 0.9286859035491943


# 4. 基于Hyperbox的NAS-Bench-101使用示例

In [6]:
import os

import torch
from nasbench import api

from hyperbox.networks.nasbench101 import NASBench101Network

In [7]:

matrix = [
    [0, 1, 1, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 1, 1],
    [0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 0, 0, 0]
]
operations = ['input', 'conv1x1-bn-relu', 'conv3x3-bn-relu', 'conv3x3-bn-relu', 'conv3x3-bn-relu', 'maxpool3x3', 'output']
spec = api.ModelSpec(matrix, operations)
query_type = 'tfrecord'
query_file = None # nasbench_full.tfrecord by default
# query_file = os.path.expanduser('~/.hyperbox/nasbench101/nasbench_only108.tfrecord')
# query_file = os.path.expanduser('~/.hyperbox/nasbench101/nasbench_full.tfrecord')
net = NASBench101Network(spec, query_type=query_type, query_file=query_file)

`NASBench101Network`提供了`query_by_key`接口，支持查询以下信息：
- 'module_adjacency':	模型的拓扑结构，表示为邻接矩阵
- 'module_operations':	模型的操作集合，表示为操作序列
- 'trainable_parameters':	模型可训练的参数数量
- 'training_time':	模型训练所需的时间
- 'train_accuracy':	模型在训练集上的准确率
- 'validation_accuracy':	模型在验证集上的准确率
- 'test_accuracy':	模型在测试集上的准确率


In [8]:
for key in ['module_adjacency', 'module_operations', 'trainable_parameters', 'training_time', 'train_accuracy', 'validation_accuracy', 'test_accuracy']:
    print(key, net.query_by_key('test_accuracy'))

Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`


Loading dataset from file... This may take a few minutes...
Loaded dataset in 241 seconds
module_adjacency 0.9221754670143127
module_operations 0.9207732081413269
trainable_parameters 0.9207732081413269
training_time 0.9275841116905212
train_accuracy 0.9221754670143127
validation_accuracy 0.9207732081413269
test_accuracy 0.9221754670143127
